'use client'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header1 from '@/copmonent/website/header1'
import Footer1 from '@/copmonent/website/footer1'
import { base_url } from '@/utils/base_url'
import axios from 'axios'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Logout from '@/copmonent/logout'
import { config } from '@/utils/axiosconfig'
// import Logout from '@/copmonent/logout'




export default function Home() {
  const router = useRouter();

  const handleLogout = () => {

    localStorage.clear();
    window.location.reload();


    //   const res = axios.get(`${base_url}user/logout`, config).then((Response) => {

    //     router.push("/login")

    // });


  }


  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <div>

          <div className="header-dark">

            <Header1 />
            <div className="container hero" style={{ height: "100mv" }}>

              <div className="row" >
                <div className="col-md-8 offset-md-2">

                  <div className="embed-responsive embed-responsive-16by9"><iframe className="embed-responsive-item"></iframe></div>
                </div>
              </div>
            </div>
          </div>

          <div className="content-wrapper ">
            <div className="row">
              <div className='container'>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
              </div>
            </div>
          </div>
        </div>
        <div style={{ textAlign: "center", color: "red" }}>
          <button style={{ textAlign: "center", color: "red", background: "green", borderColor: "white", padding: "10px", margin: "10px", borderRadius: "20px 2px 20px 2px", boxShadow: "rgba(0, 0, 0, 0.56) 0px 22px 70px 4px" }}
            onClick={handleLogout}>Logout
          </button>
        </div>


        <Footer1 />
      </main>

    </>
  )
}
