import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import Header from '@/copmonent/user/header'
import Sidebar from '@/copmonent/super_admin/sidebar'
import Footer from '@/copmonent/user/footer'

import Skin from '@/copmonent/user/skin'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect } from 'react'
import { getUsers } from '../features/customers/customerSlice'


// const inter = Inter({ subsets: ['latin'] })

export default function SuperAdminList() {

    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(getUsers());
    }, []);
    const customerstate = useSelector((state) => state.customer.customers);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container-scroller">
                    <Header />
                    <div className="container-fluid page-body-wrapper">
                        <Skin />

                        <Sidebar />
                        <div className="main-panel">
                            <div className="content-wrapper">


                                <div className="row">
                                    <div className="col-md-12 grid-margin stretch-card">
                                        <div className="card">
                                            <div className="card-body">
                                                <p className="card-title ">Transections </p>
                                                <div className="table-responsive">
                                                    <table className="table  display expandable-table">

                                                        <thead>
                                                            <tr>
                                                                <th>S.no</th>
                                                                <th>Name</th>
                                                                <th>Mobile no.</th>
                                                                <th>Profile</th>
                                                            </tr>
                                                        </thead>
                                                        {customerstate.map((value, key) => {
                                                            return (
                                                                <tbody  >
                                                                    <tr>
                                                                        <td>{key + 1}</td>
                                                                        <td >{value.name} </td>
                                                                        <td>{value.mobile}</td>
                                                                        <td className="font-weight-medium"><div className="badge badge-success">Profile</div></td>
                                                                    </tr>

                                                                </tbody>
                                                            )
                                                        })}
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>


                            </div>
                            <Footer />


                        </div>
                    </div>
                </div>

            </main >
        </>
    )
}