import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import Header from '@/copmonent/user/header'
import Sidebar from '@/copmonent/user/sidebar'
import Footer from '@/copmonent/user/footer'
import Rightsidbar from '@/copmonent/user/right-sidebar'
import Skin from '@/copmonent/user/skin'


// const inter = Inter({ subsets: ['latin'] })

export default function PaymentTable() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container-scroller">
                    <Header />
                    <div className="container-fluid page-body-wrapper">
                        <Skin />
                        <Rightsidbar />
                        <Sidebar />
                        <div className="main-panel">
                            <div className="content-wrapper">


                                <div className="row">
                                    <div className="col-md-12 grid-margin stretch-card">
                                        <div className="card">
                                            <div className="card-body">
                                                <p className="card-title ">Transections</p>
                                                <div className="table-responsive">
                                                    <table className="table  display expandable-table">
                                                        <thead>
                                                            <tr>
                                                                <th>S.no</th>
                                                                <th>Name</th>
                                                                <th>Transection no.</th>
                                                                <th>Amount</th>
                                                                <th>Mode of payment</th>
                                                                <th>Date</th>
                                                                <th>Status</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>1.</td>
                                                                <td >xyzab </td>
                                                                <td>9879278397823</td>
                                                                <td className="font-weight-bold">₹362</td>
                                                                <td >online</td>
                                                                <td>21 Sep 2018</td>
                                                                <td className="font-weight-medium"><div className="badge badge-success">Completed</div></td>
                                                            </tr>
                                                            <tr>
                                                                <td>2.</td>
                                                                <td>xyzabc</td>
                                                                <td>9879278397823</td>
                                                                <td className="font-weight-bold">$523</td>
                                                                <td>online</td>
                                                                <td>30 Jun 2018</td>
                                                                <td className="font-weight-medium"><div className="badge badge-warning">Pending</div></td>
                                                            </tr>
                                                            <tr>
                                                                <td>3.</td>
                                                                <td>xyzabc</td>
                                                                <td>9879278397823</td>
                                                                <td className="font-weight-bold">$781</td>
                                                                <td>online</td>
                                                                <td>01 Nov 2018</td>
                                                                <td className="font-weight-medium"><div className="badge badge-danger">Cancelled</div></td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>


                            </div>
                            <Footer />


                        </div>
                    </div>
                </div>

            </main>
        </>
    )
}